# ActionsPlane — Makefile
# Python-first control plane. uv-managed.

SHELL := /bin/bash
.DEFAULT_GOAL := help

PY      := uv run
COMPOSE := docker compose -f deploy/docker-compose.yml

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

# --- setup ---
.PHONY: install
install: ## Install deps (incl. dev extras) into a uv-managed venv
	uv sync --extra dev

# --- dev stack ---
.PHONY: up down logs up-full seed
up: ## Start Postgres + Redis dev stack
	$(COMPOSE) up -d

down: ## Stop the dev stack
	$(COMPOSE) down

logs: ## Tail dev-stack logs
	$(COMPOSE) logs -f

up-full: ## Start the full stack in Docker (PG+Redis+migrate+api+ingestor+worker)
	docker compose -f deploy/docker-compose.full.yml up --build

seed: ## Seed a demo installation/repos/runs so the API/UI aren't empty (no GitHub needed)
	PYTHONPATH=src $(PY) python scripts/seed_local.py

# --- run ---
.PHONY: api ingestor worker
api: ## Run the REST/GraphQL API (FastAPI)
	$(PY) uvicorn actionsplane.api.app:app --reload --port 8000

ingestor: ## Run the webhook ingestor (FastAPI)
	$(PY) uvicorn actionsplane.ingestor.app:app --reload --port 8001

worker: ## Run the async sync/executor worker (arq)
	$(PY) arq actionsplane.sync.worker.WorkerSettings

# --- db ---
.PHONY: migrate revision
migrate: ## Apply DB migrations
	$(PY) alembic upgrade head

revision: ## Create a new autogenerated migration (NAME=...)
	$(PY) alembic revision --autogenerate -m "$(NAME)"

# --- test / lint ---
.PHONY: test lint fmt
test: ## Run unit tests
	$(PY) pytest -q

lint: ## Lint + format check
	$(PY) ruff check .
	$(PY) ruff format --check .

fmt: ## Auto-format
	$(PY) ruff format .
	$(PY) ruff check --fix .

# --- cli ---
.PHONY: cli
cli: ## Show the actionsplane CLI help
	$(PY) actionsplane --help
